services:
  node:
    build:
      context: .
      target: node
    environment:
      - NODE_ENV=development
    env_file:
      -  ./.env
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
    depends_on:
      - mariadb
    volumes:
      - ".:/app"


  mariadb:
    image: mariadb:11.2.2
    environment:
      MARIADB_HOST: mariadb 
      MARIADB_USER: mariauser
      MARIADB_PASSWORD: mariapassword
      MARIADB_DATABASE: dbmaria
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - "./docker/mariadb/data:/var/lib/sql"

  adminer:
    image: adminer
    ports:
      - 8080:8080
