services:
  node:
    build:
      context: .
      target: node
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
    restart: "always"
    depends_on:
      - mariadb
    volumes:
      - ".:/app"


  mariadb:
    image: mariadb:11.2.2
    environment:
      MARIADB_HOST: ${DB_HOST}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - "./docker/mariadb/data:/var/lib/sql"
