version: '3.8'
services:
  node:
    image: ghcr.io/boutroisjordan/final-test-boutroisjordan-node:develop
    environment:
      NODE_ENV: development
    networks:
      - frontend
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.express-http-dev.rule=Host(`ec2-50-17-33-51.compute-1.amazonaws.com`)"
      - "traefik.http.routers.express-http-dev.entrypoints=web"
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - ./.env
    command: ["npm", "run", "start"]

  mariadb:
    image: mariadb:11.2.2
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 20s
      retries: 10
    networks:
       - backend
    environment:
      MARIADB_HOST: ${DB_HOST}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - "./docker/mariadb/data:/var/lib/mysql"

networks:
  frontend:
    external: true
    name: custom_frontend

  backend:
    external: true
    name: custom_backend

