name: CICD
on:
  push:
    branches:
      - main
      - develop  # Ajoutez la branche sur laquelle vous souhaitez déclencher le workflow
env:
  REGISTRY: ghrc.io
  IMAGE_NAME: boutroisjordan/final-test-boutroisjordan-node
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
jobs:

  buildDocker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GTHB_TOKEN }}

      - name: Set Docker image tag based on branch
        id: set-tag
        run: echo "TAG=$(if [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then echo 'develop'; else echo 'latest'; fi)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build --tag ghcr.io/${{env.IMAGE_NAME}}:${{ env.TAG }} --platform linux/amd64 .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{env.IMAGE_NAME}}:${{ env.TAG }}

  testDocker:
    needs: buildDocker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: echo "DB_HOST=${DB_HOST}\nDB_USER=${DB_USER}\nDB_PASSWORD=${DB_PASSWORD}\nDB_DATABASE=${DB_DATABASE}" > .env

      - run: docker compose --env-file .env up -d --build
      - run: sleep 30
      - run: docker compose exec node npm run test